default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root

development:
  <<: *default
  database: db/nicomoni_development

test:
  <<: *default
  database: db/nicomoni_test

production:
  <<: *default
  database: db/nicomoni_production
